language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

install:
  - pip install coveralls

# command to run tests
script:
  coverage run --source=incoming setup.py test

after_success:
  coveralls
